### ISSUE TITLE
Use org.opentest4j.AssertionFailedError to report error when available

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1072]
#### Summary

JUnit 5 throws `org.opentest4j.AssertionFailedError` when an `assertEquals` fails, IDEs (Idea at least) show a nice diff view of the error.
AssertJ should also throw `org.opentest4j.AssertionFailedError` when an `isEqualTo` and `org.opentest4j.AssertionFailedError` is available in the classpath. We had a simliar approach with JUnit 4 and `org.junit.ComparisonFailure`.

#### Java 8 specific ?

* NO  : Pull Request should be from the `2.x` branch

**Comment by filiphr** [comment]
I've started working on this and it is not difficult to add support. However, I noticed that IntelliJ only takes advantage of the `AssertionFailedError` in JUnit5. This means that if we throw `AssertionFailedError` in a JUnit4 test it would not work correctly. I am not sure what would happen if we do the opposite. 

To solve this, I would first check for `ComparisonFailure`, then `AssertionFailedError`. The reason is that most probably people will have both on the classpath during their migrations.

In any case I've created [IDEA-1794820](https://youtrack.jetbrains.com/issue/IDEA-1794820) for IntelliJ so they add support globally.

**Comment by joel-costigliola** [comment]
I think if JUnit4 and JUnit5 are in the classpath then it should not really matter which one we choose as it will be reported correctly in IDEA. I would choose JUnit 4 `ComparisonFailure` though for people using IDEs not supporting JUnit5 yet.
