### ISSUE TITLE
BigDecimal isBetween fails when end is a different scope

### ISSUE THREAD

**Issue by craigbensemann** [joel-costigliola/assertj-core#1177]
#### Summary

While upgrading from `3.1.0` to `3.9.0` a unit test using `isBetween` started to fail with the message `The end value <1.70> must not be less than the start value <1.7000000>!`. 

It appears that the default comparisonStrategy (`StandardComparisonStrategy`) is being used which in the end uses `Objects.areEqual(actual, other)`. This is in conflict with the javadoc for isBetween _"Note that comparison of {@link BigDecimal} is done by value without scale consideration, i.e 2.0 and 2.00 are considered equal in value"_

#### Example

This now fails with 3.9.0
```java
assertThat(new BigDecimal("1.70000")).isBetween(new BigDecimal("1.7000"), new BigDecimal("1.7"));
```

Adding a custom comparator makes the assertion pass.
```java
assertThat(new BigDecimal("1.70000")).usingComparator(BigDecimal::compareTo).isBetween(new BigDecimal("1.7000"), new BigDecimal("1.7"));
```

I think this is a regression issue and a custom comparator shouldn't be needed but it could have been done by design?

Thanks
Craig

**Comment by joel-costigliola** [comment]
It is likely a regression, good catch!

**Comment by joel-costigliola** [comment]
The behavior change was introduced in 0ce73a863b8d3129af28492eaf1fd81ad1e110d7 when we started to check that `start <= end`.

The obvious fix would be to use `BigDecimal` comparator internally but this is actually a breaking change since the default comparison strategy is to use `BigDecimal.equals` for equal and not `BigDecimal.compareTo`.

Anyway I think it is better to change the comparison strategy to be based on `BigDecimal.compareTo` (except for `isEqualTo` that should honor `BigDecimal.equals` as users have `isEqualByComparingTo` to use `BigDecimal.compareTo`).

**Comment by joel-costigliola** [comment]
Fixed

**Comment by craigbensemann** [comment]
great. thanks!
