### ISSUE TITLE
Use soft assertions all the time

### ISSUE THREAD

**Issue by Jcamilorada** [joel-costigliola/assertj-core#1244]
I have been discussing internally with a co worker, the possibility to start using only soft assertions  for 100% of our unit test and integration test suites assertions (when more than one assertion in test).

As a project administration would you recommend this practice?

**Comment by joel-costigliola** [comment]
IMO, using soft assertion is valuable when you have tests that are expensive to run, for this type of tests you want to gather all the errors so that you can fix them all at once and avoid rerunning the tests just to discover that the assertions after the one that failed was also failing.

Soft assertions comes at a cost in performance, they use a proxy mechanism which is expensive at the proxy creation time (after that phase it's alright).

When testing a class or method, I prefer write a lot of small tests covering each aspects of the behavior to verify (like [Files_linesOf_Test](https://github.com/joel-costigliola/assertj-core/blob/master/src/test/java/org/assertj/core/util/Files_linesOf_Test.java)), with this strategy you don't need soft assertions since usually there is only one or two assertions.

**Comment by joel-costigliola** [comment]
@Jcamilorada Does that answer your question ?

**Comment by jcamiloradamesa** [comment]
Hi yes, thanks for the time you expend with explanation :)

**Comment by Jcamilorada** [comment]
yes! many thanks!
