### ISSUE TITLE
Fluent assertions on the toString of an Object

### ISSUE THREAD

**Issue by ianbrandt** [joel-costigliola/assertj-core#1307]
#### Summary

Similar to fluent assertions on the `size()` of an `Iterable` (#301), it would be handy to have the same for the `toString()` of an `Object`.

#### Example

```java
assertThat(object).hasToString().contains("text");
```

Currently there's only `hasToString(String)`, which asserts an exact match.

Of note, this example perhaps doesn't read as nice as say, `assertThat(object).asString().contains(...)`.  As currently defined, [asString()](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractAssert.html#asString--) fails if `object` is not an instance of `String`, making that approach a breaking change.

As a workaround I'm following the recommendation in https://github.com/joel-costigliola/assertj-core/issues/357#issuecomment-89548008, and doing:

```java
assertThat(object.toString()).contains("text");
```

...however, this results in a `NullPointerException` instead of a nice `AssertionError` in the event `object` is null.

**Comment by joel-costigliola** [comment]
I feel `assertThat(object).hasToString().contains("text");` does not read well, I would go with `assertThat(object).asString().contains(...)`. It is breaking change indeed but a minor one because if the object is a `String` then the behavior is unchanged and `isIstanceOf(String.class)` can always be used to verify the object is a `String`.

**Comment by joel-costigliola** [comment]
Integrated thanks @ianbrandt !

**Comment by ianbrandt** [comment]
Happy to help!  Looking forward to 3.12.
