### ISSUE TITLE
Recursive comparison should to compare Optional field values recursively

### ISSUE THREAD

**Issue by nazartm** [joel-costigliola/assertj-core#1424]
#### Summary
When using `isEqualToComparingFieldByFieldRecursively` with classes that contain optional fields, the comparison fails by comparing reference instead of the fields.

Expected solution would be to check if optional is present and compare the fields in the optional value.

The below unit test can be used to test the case.

#### Example

```java
class Author {

    private String name;

    public Author(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}

class Book {

    private Optional<Author> coAuthor;

    public Book(Author author) {
        this.coAuthor = Optional.ofNullable(author);
    }

    public Optional<Author> getCoAuthor() {
        return coAuthor;
    }
}

public class SimpleOptionalTest {

    @Test
    public void testOptionalField() {
        Book book1 = new Book((new Author("test")));
        Book book2 = new Book((new Author("test")));
        assertThat(book1).isEqualToComparingFieldByFieldRecursively(book2);
    }
}
```

**Comment by saurabh-ku** [comment]
We can box the objects inside any custom wrapper we build, not just an optional. How do we figure out how to extract the internal object?

**Comment by nazartm** [comment]
But it's not a customer wrapper, it's part of java.

**Comment by joel-costigliola** [comment]
The issue here is that it uses `Optional` equals method to compare the `coAuthor` field which then compares the authors.

What needs to be done is treat `Optional` as collections are treated and compare their content recursively instead of using `equals` (by default the recursive comparison uses `equals` on types where it had been redefined).

The new recursive  API (#1002) that has been released yesterday allows to force recursive comparison even for types redefining `equals` but unfortunately this is exclude java types.

We will fix that issue on new recursive API (and make  `isEqualToComparingFieldByFieldRecursively` to call it).

**Comment by joel-costigliola** [comment]
I did not change ` isEqualToComparingFieldByFieldRecursively`  because it would be a breaking change, I just deprecated it.

**Comment by joel-costigliola** [comment]
Has been addressed in https://github.com/joel-costigliola/assertj-core/commit/e2b4828b7d066fde9b0664f00000b58b0d2bbe4e and improved in https://github.com/joel-costigliola/assertj-core/commit/f32974846381c94d9bd7436e3ba98163a96cd97c
