### ISSUE TITLE
Review Truth-AssertJ comparison (if you're interested)

### ISSUE THREAD

**Issue by cpovirk** [joel-costigliola/assertj-core#1543]
Hi, we (owners of [Google Truth](https://truth.dev/), a library similar to AssertJ) have recently updated our [comparison of Truth and AssertJ](https://truth.dev/comparison) in preparation for our release 1.0. Well, OK, it's presented more as a sales pitch for Truth :) Still, while we may always see some things differently than you do, we don't want to be outright inaccurate. Plus, we figure it's better to let you know about the page in case you want to have a look, rather than talk about you "behind your back," so to speak :) Feel free to have a look, but of course no obligation. 1.0 is coming on Monday, FYI.

**Comment by joel-costigliola** [comment]
Thanks @cpovirk I'll have a look.
Congrats for the upcoming 1.0 release!

**Comment by joel-costigliola** [comment]
A first comment: the javadoc API is now published here: https://www.javadoc.io/doc/org.assertj/assertj-core the one linked in your page points to a slightly older version.

**Comment by joel-costigliola** [comment]
@cpovirk maybe you could point out these features:
* [soft assertions](https://assertj.github.io/doc/#assertj-core-soft-assertions) (record all failures instead of stopping at the first one)
* [assumptions](https://assertj.github.io/doc/#assertj-core-assumptions)
* [recursive comparison](https://assertj.github.io/doc/#assertj-core-recursive-comparison) to compare objects as data structures.
* [Guava assertions](http://joel-costigliola.github.io/assertj/assertj-guava.html)  ;-)

**Comment by cpovirk** [comment]
Thanks! I just pushed some changes.
