### ISSUE TITLE
extracting(properties...).doesNotContainNull will not check every property, but aggregate

### ISSUE THREAD

**Issue by MrR0807** [joel-costigliola/assertj-core#1546]
#### Summary
When extracting multiple properties, I would expect that each property is compared separately, however, under the hood those properties are aggregated into an object of Tuple and then asserted. Even if one of Tuple property is null, it will pass the assertion anyway.

#### Example

```

    @Test
    public void doesNotContainNull__whenMultiplePropertiesExtracted() {
        var list = List.of(new Example(1, 2, 3), new Example(1, 2, null));

        assertThat(list).extracting("one", "two", "three").doesNotContainNull(); //pass
    }

    @Test
    public void doesNotContainNull__whenOneAtATimePropertyExtracted() {
        var list = List.of(new Example(1, 2, 3), new Example(1, 2, null));

        assertThat(list).extracting("one").doesNotContainNull(); //pass
        assertThat(list).extracting("two").doesNotContainNull(); //pass
        assertThat(list).extracting("three").doesNotContainNull(); //fail
    }
}

class Example {
    private Integer one;
    private Integer two;
    private Integer three;

    public Example(Integer one, Integer two, Integer three) {
        this.one = one;
        this.two = two;
        this.three = three;
    }

    public Integer getOne() {
        return one;
    }

    public Integer getTwo() {
        return two;
    }

    public Integer getThree() {
        return three;
    }
}
```

**Comment by joel-costigliola** [comment]
The idea of extracting multiple properties is to perform assertions on the grouped extracted properties, this is why they are extracted and put in a tuple.

The behavior you are experiencing is as expected, your example succeeds because no there is not null tuple in the extracted list of tuples.

>  assertThat(list).extracting("one", "two", "three").doesNotContainNull(); 

If you want to check for null values, you either check properties individually (as you did in `doesNotContainNull__whenOneAtATimePropertyExtracted`) or write a `Condition<Tuple>` that checks for absence of null elements.
