### ISSUE TITLE
Use assertThatAssertionErrorIsThrownBy instead of assertThatThrownBy(() -> ...).isInstanceOf(AssertionError.class)

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1611]
#### Summary

`AssertionsUtil.assertThatAssertionErrorIsThrownBy` checks the caught throwable is an `AssertionError`.
Make sure the tests are written following the GIVEN WHEN THEN pattern

#### Example

```java
CompletableFuture<String> future = new CompletableFuture<>();

assertThatThrownBy(() -> assertThat(future).hasFailed()).isInstanceOf(AssertionError.class)
                                                        .hasMessage(shouldHaveFailed(future).create());
```
should be written as
```java
// GIVEN
CompletableFuture<String> future = new CompletableFuture<>();
// WHEN
ThrowingCallable code = () -> assertThat(future).hasFailed();
// THEN
assertThatAssertionErrorIsThrownBy(code).withMessage(shouldHaveFailed(future).create());
```
Note the use of GIVEN WHEN THEN to clarify the test steps.

**Comment by cgrabmann** [comment]
working on it

**Comment by cgrabmann** [comment]
@joel-costigliola By now I just replaced every occurance in the CompletableFutureAssert tests, as well as replaced and refactored all LocalDateAssert and all InstantAssert tests to follow the current test guidelines. I still have to do all LocalDateTimeAssert, LocalTimeAssert and OffsetDateTimeAssert tests and I already have around 30 changed files.
Since big PRs aren't much fun, would you like the changes in batches or in one big bulk?

**Comment by joel-costigliola** [comment]
Good idea, let's split the PR in per type.

**Comment by fdooom663** [comment]
Gfdnvzh

**Comment by quaythuoc-org** [comment]
Thanks you about this

**Comment by MilkTimeplus** [comment]
wow, difficult, I couldn't understand it

**Comment by chandra20sekhar** [comment]
i didn't understand it
