### ISSUE TITLE
Compare enums with usingRecursiveComparison

### ISSUE THREAD

**Issue by Pryanic** [joel-costigliola/assertj-core#1691]
#### Summary
Hi, I found a very confused limitations, I don't now why this happens bet let's fix it.
I have simple class structure 

#### Example

```java
  static enum A{
        B,
        C
    }
    @AllArgsConstructor
    static class Check{
        public A value;
    }

    public static void main(String[] args) {
        Check actual = new Check(A.B);
        Check expected = new Check(A.C);
        assertThat(actual)
            .usingRecursiveComparison()
            .ignoringAllOverriddenEquals()
            .isEqualTo(expected);

    }
```

This test passes. I don't understand why 
Can you help with it.  I don't want remove usingRecursiveComparison and ignoringAllOverriddenEquals

**Comment by Pryanic** [comment]
I've found the solution custom comparator for enum fields 
`.withComparatorForType(comparator,Enum.class)`

**Comment by joel-costigliola** [comment]
We will look into that behavior, does not feel right

**Comment by Pryanic** [comment]
@joel-costigliola  thank you for you response. Let me know if you need more information

**Comment by joel-costigliola** [comment]
Git a bit of time to look at it, the reason the test does not fail is that the `value` field in actual `Check` is compared recursively against expected. It turns out that enum fields are static and static fields are ignored in the recursive comparison since the point is to compare instances not classes.

I think ignoring static fields is valid, the issue here is that we try to compare enum recursively when they should be compared with equals (or == since it's the same for enum) .

**Comment by Pryanic** [comment]
@joel-costigliola Thank you.
