### ISSUE TITLE
Java6AbstractStandardSoftAssertions should be abstract

### ISSUE THREAD

**Issue by m-g-sonar** [joel-costigliola/assertj-core#1704]
#### Summary
We are working on support of AssertJ's `Java6SoftAssertions` in SonarJava static analyzer, The plugin for SonarQube covering Java. More precisely, we are working at removing False Positives currently raised by rule [S2699: Tests should include assertions](https://rules.sonarsource.com/java/RSPEC-2699).

It is specified in the documentation that `Java6AbstractStandardSoftAssertions` is duplicated from `AbstractStandardSoftAssertions` which is `abstract`.
However, `Java6AbstractStandardSoftAssertions` is not abstract so it can be instantiated. Consequently, and because this class does not contain `assertAll()` method, any test which will use  an instance of this class will always pass.

Shouldn't `Java6AbstractStandardSoftAssertions` be abstract?

We can provide a PR fixing it.
#### Example

```java
class A {
  int foo(int i) {
    if (i > 0) {
      return 42;
    }
    return -1;
  }
}

class ATest {
  @Test
  void test() { // My test will never fail
    org.assertj.core.api.Java6AbstractStandardSoftAssertions myAssert = new org.assertj.core.api.Java6AbstractStandardSoftAssertions();
    myAssert.assertThat(new A().foo(0)).isEqualTo(42);
    myAssert.assertThat(new A().foo(0)).isEqualTo(-1);
  }
}
```

**Comment by joel-costigliola** [comment]
We'll have a look but you are likely right that this class can be made not abstract.
If you are working on assertions best practices, there are a few things that can be done for AssertJ, they are described here: https://assertj.github.io/doc/#assertj-core-incorrect-usage

**Comment by m-g-sonar** [comment]
>  you are likely right that this class can be made not abstract.

I think that's the opposite, `Java6AbstractStandardSoftAssertions` should be made `abstract`, for consistency.

Thanks a lot for the pointer on assertj incorrect usage page, I didn't know about it, and there is most probably something we could do to cover them!

**Comment by joel-costigliola** [comment]
Ah ah right, I should not have replied without access to my IDE.

**Comment by scordio** [comment]
Hi @m-g-sonar, I have two related questions about rule [S2699](https://rules.sonarsource.com/java/RSPEC-2699).

Assuming this rule is enabled for AssertJ internal build, there are some tests which should pass if nothing was thrown (e.g., `should_pass_if_optional_contains_required_type` mentioned in [CONTRIBUTING](https://github.com/joel-costigliola/assertj-core/blob/master/CONTRIBUTING.md)). At the moment there is no assertion for it, we just rely on non-failure from the JUnit execution.

Reading the rule description, most likely these tests should be detected as noncompliant, but probably they would be considered compliant because `org.assertj.core.api.Assertions.assertThat` itself is the actual test target.

Will there be a way to exclude an assertion method from the default rule list?

Then, assuming `assertThat` is not considered an assertion method anymore, instead of writing:
```java
  @Test
  void should_pass_if_optional_contains_required_type() {
    // GIVEN
    Optional<String> optional = Optional.of("something");
    // WHEN
    assertThat(optional).containsInstanceOf(String.class);
  }
```

we should write something like:
```java
  @Test
  void should_pass_if_optional_contains_required_type() {
    // GIVEN
    Optional<String> optional = Optional.of("something");
    // WHEN
    AssertionError assertionError = expectAssertionError(() -> assertThat(optional).containsInstanceOf(String.class));
    // THEN
    then(assertionError).isNull();
  }
```
which is a bit more verbose. Is it the style you would expect?

I can imagine I am mentioning two corner cases (throwables and AssertJ internal testing), but it would be great to know your opinion about it.

**Comment by joel-costigliola** [comment]
reopening for @scordio question ...
