### ISSUE TITLE
Provide a non-list alternative to "extracting"

### ISSUE THREAD

**Issue by MrBuddyCasino** [joel-costigliola/assertj-core#1706]
#### Summary

The `.extracting(<someMethod>).first().` is unintuitive. As a first time AssertJ user, I just spent several minutes wondering why the tst failed until I discovered that `extracting` returns a list, not a single object. I understand why, but having a non-list alternative like `extract` or `map` would be more readable and intutive.

#### Example

```java
Service accountService = new Service("account-service", rule);
cache.update(accountService, "/common/account/user/456");
Set<EntityWithMetadata<Service>> byPath = cache.findByPath("/common/account/user/456");
// current
assertThat(byPath).first().extracting(EntityWithMetadata::getEntity).first().isEqualTo(accountService);
// desired
assertThat(byPath).first().map(EntityWithMetadata::getEntity).isEqualTo(accountService);
```

**Comment by scordio** [comment]
Since `assertj-core` 3.11.0, [`extracting(Function)`](https://javadoc.io/doc/org.assertj/assertj-core/3.11.0/org/assertj/core/api/AbstractObjectAssert.html#extracting-java.util.function.Function-) provides an `AbstractObjectAssert`. Are you using a recent version of AssertJ?

I tried to reproduce the issue using the current version and it seems to work correctly:
```java
class EntityWithMetadata {
  private final String entity;

  EntityWithMetadata(String entity) {
    this.entity = entity;
  }

  String getEntity() {
    return entity;
  }
}

@Test
void test() {
  Set<EntityWithMetadata> byPath = Collections.singleton(new EntityWithMetadata("account-service"));

  assertThat(byPath) // IterableAssert<EntityWithMetadata>
    .first() // ObjectAssert<EntityWithMetadata>
    .extracting(EntityWithMetadata::getEntity) // AbstractObjectAssert<?, String>
    .isEqualTo("account-service");
}
```

**Comment by joel-costigliola** [comment]
I think the issue here is that @MrBuddyCasino used `extracting` before `first`, is that right @MrBuddyCasino? 

Changing `extracting` to `map` would not change anything as both would return an iterable if given one, we might add `map` as an alias for `extracting` (but I'm not so sure it is worth bloating the API).

FYI `extracting` has been introduced before java 8, it was a time when `map` was for in Java

**Comment by MrBuddyCasino** [comment]
> Since 3.11.0, [`extracting(Function)`](https://javadoc.io/doc/org.assertj/assertj-core/3.11.0/org/assertj/core/api/AbstractObjectAssert.html#extracting-java.util.function.Function-) returns an `AbstractObjectAssert`. Are you using a recent version of AssertJ?

You got me there, due to a problem with a dependency we're stuck at 3.9.1. I tested with 3.11.0 and the second `.first()` call has indeed become obsolete. Thanks for checking, looks like you're ahead of me. Thanks for making AssertJ, its nicer to use than Hamcrest! :)

**Comment by joel-costigliola** [comment]
thanks for the kind words @MrBuddyCasino!
