### ISSUE TITLE
Improve the error message on contains method

### ISSUE THREAD

**Issue by mdeinum** [joel-costigliola/assertj-core#1746]
When using AssertJ and in this specific case using `extracting("name1", "name2").contains(val1, val2)` or the functional one `extracting(it -> it.getName1(), it -> it.getName()).contains(val1, val2)`. In case of a value not matching the error message is not as descriptive as one likes to be. 

Currently it is :
```
Expecting:
  <[null, 2019-12-05T07:57:38.531, null]>
to contain exactly (and in same order):
  <[null, 2019-12-05T07:57:38.531, null]>
but some elements were not found:
  <[2019-12-05T07:57:38.531]>
and others were not expected:
  <[2019-12-05T07:57:38.531]>
```
And at first glance it isn't apparent what is wrong, as the values appear to match. However as it turned one one was a `LocalDateTime` and the other a `java.util.Date`. 

When comparing a single property with `isEqualTo` the error message is more descriptive

```
java.lang.AssertionError: 
Expecting:
 <"2019-12-05T07:59:56.439 (LocalDateTime@43f02ef2)">
to be equal to:
 <"2019-12-05T07:59:56.439 (Date@239a307b)">
but was not.
```

Now it is directly apparent what the error is as the type and hashcode is included in the error message. 

It would be beneficial of the message from contains could also include the type and hashcode in the error message.

**Comment by joel-costigliola** [comment]
Indeed  when `actual` and `expected` have the same representation `isEqualTo` will replace their default representation with unambiguous ones (adding the type and the identity hash code).

Ideally we would do that for all assertions when representations are the same too but it is not straightforward (and sometimes not even possible) to decide which objects should be displayed  unambiguously (although in your example it could work as we are comparing pair of elements). The only solution then is to represent everything unambiguously all the time in the default representation even when the displayed objects have clearly different representations.

My first thoughts is that it might be a bit too much noise in the error messages if every single value is represented in its unambiguous form.

Maybe an intermediate solution would be to provide a `UnambiguousStandardRepresentation` which basically would use the standard representation and add the type + identify values. The code is 99% there since `StandardRepresentation` already has [unambiguousToStringOf](https://github.com/joel-costigliola/assertj-core/blob/b82b86b2c54bb33c09103744ea0d7af4b37b4dee/src/main/java/org/assertj/core/presentation/StandardRepresentation.java#L200).

Since AssertJ allows to [specify a representation](https://assertj.github.io/doc/#assertj-core-representation) globally, once you have written your own `UnambiguousStandardRepresentation` you can easily use it everywhere.

Thinking out loud, this could be something AssertJ out of the box in its [`Configuration`](https://assertj.github.io/doc/#assertj-configuration), something like:
```
configuration.useUnambiguousStandardRepresentation();
```


BTW that's not the `contains` assertion I'm pretty sure it's `containsExactly` ;-)

**Comment by joel-costigliola** [comment]
Another option would be to just change the default representation of dates to be unambiguous, since these are classes could most likely have identical representations.

**Comment by joel-costigliola** [comment]
@mdeinum I'm think to go as per my previous comment, that is adding the class name after the object representation, ex: `2019-12-05T07:57:38.531 (java.time.LocalDateTime)`.
WDYT?

**Comment by mdeinum** [comment]
That would work, as one can then also see the type differences next to the string differences (which probably aren't there in those cases).

**Comment by joel-costigliola** [comment]
FYI I have added the class name to the representation of instances of the following classes:
* LocalDate
* LocalDateTime
* OffsetDateTime
* ZonedDateTime
* Date
* Calendar

**Comment by joel-costigliola** [comment]
Here's what it looks like now with the following failing test:
```java
Date now = new Date();
Object localDateTime = LocalDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault());

assertThat(List.of(localDateTime)).containsExactly(now);
```
error:
```
java.lang.AssertionError: 
Expecting:
  <[2020-03-19T22:32:42.875 (java.time.LocalDateTime)]>
to contain exactly (and in same order):
  <[2020-03-19T22:32:42.875 (java.util.Date)]>
but some elements were not found:
  <[2020-03-19T22:32:42.875 (java.util.Date)]>
and others were not expected:
  <[2020-03-19T22:32:42.875 (java.time.LocalDateTime)]>
```
