### ISSUE TITLE
assertThat(Double.NaN).isEqualTo(Double.NaN) fails

### ISSUE THREAD

**Issue by cheister** [joel-costigliola/assertj-core#1783]
#### Summary
`assertThat(Double.NaN).isEqualTo(Double.NaN);` fails with 

```
[ERROR] Failures: 
[ERROR]   Doubles_assertEqual_Test.should_pass_if_doubles_are_NaN 
Expecting:
 <"NaN (Double@691505cf)">
to be equal to:
 <"NaN (Double@79f3359e)">
but was not.
```

#### Example

```java
  @Test
  public void should_pass_if_doubles_are_NaN() {
    assertThat(Double.NaN).isEqualTo(Double.NaN);
  }
```

It seems like this is related to https://github.com/joel-costigliola/assertj-core/issues/1715 ? but it still fails on master if I add the above test to src/test/java/org/assertj/core/internal/doubles/Doubles_assertEqual_Test.java

I tried `doubles.assertEqual(someInfo(), Double.NaN, Double.NaN);` also and that still works

**Comment by joel-costigliola** [comment]
This is indeed related to #1715 and a breaking change in [3.15.0](https://assertj.github.io/doc/#assertj-core-3-15-0-release-notes).

`Double.NaN` being a primitive `double` AssertJ now use `==` instead of `equals` to compare them.
As per [Double.equals](https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#equals-java.lang.Object-) javadoc:
> If d1 and d2 both represent Double.NaN, then the equals method returns true, even though Double.NaN==Double.NaN has the value false. 

The error message is a bit confusing in that it shows `Double`, this certainly can be improved.

I'll also mention explicitly in the release notes that `NaN` comparison changed in 3.15.0.

**Comment by joel-costigliola** [comment]
If you really want to get the pre 3.15.0 behavior, you can convert the expected value to `Double`.

**Comment by cheister** [comment]
Got it.  Casting it to `Double` worked.

Following the java standard makes sense as a rule but it's surprising that I'll have to remember to cast any `double`s to `Double`s to assert equality on all values of double. 

Thanks for the quick response.

**Comment by joel-costigliola** [comment]
>  it's surprising that I'll have to remember to cast any doubles to Doubles to assert equality on all values of double.

That will not work either for all values as if d1 represents +0.0 while d2 represents -0.0, or vice versa, the equal test has the value false, even though +0.0==-0.0 has the value true. (as stated in https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#equals-java.lang.Object-).

Anyway I'm happy I could help

**Comment by joel-costigliola** [comment]
Just reopening the issue to provide a better error message when comparing NaN
