### ISSUE TITLE
Casting object under test and returning new assertion on some operations

### ISSUE THREAD

**Issue by joca-bt** [joel-costigliola/assertj-core#1797]
I find myself doing something similar to the following quite frequently:

```
assertThat(object).isInstanceOf(String.class);
assertThat((String) object).matches(pattern);
```

Would it make sense to cast the object under test and return the corresponding assertion? For example:

```
assertThat(object).isInstanceOf(String.class).matches(pattern);
```

`first()` (for lists) and `extracting()` (for maps) already do something like this.

**Comment by joca-bt** [comment]
`asInstanceOf` was added in 3.13. Wwe're using 3.12 that's why we didn't noticed it.

**Comment by scordio** [comment]
[`asInstanceOf`](https://www.javadoc.io/static/org.assertj/assertj-core/3.15.0/org/assertj/core/api/AbstractAssert.html#asInstanceOf(org.assertj.core.api.InstanceOfAssertFactory)) is probably what you are looking for.

Also, since 3.14 `first()`, `extracting()` and other methods have the overloaded variant to support an `InstanceOfAssertFactory`. You can see the full list in the `@see` section of [`Assertions.as()`](https://www.javadoc.io/static/org.assertj/assertj-core/3.15.0/org/assertj/core/api/Assertions.html#as(org.assertj.core.api.InstanceOfAssertFactory)) javadoc.

**Comment by scordio** [comment]
@joca-bt I close this issue. In case you need more info, please let us know.
