### ISSUE TITLE
Fail assertion on MapAssert.containsExactly when the Map implementation is not sorted

### ISSUE THREAD

**Issue by apupier** [joel-costigliola/assertj-core#327]
When checking MapAssert.containsExactly on a HashMap for instance, the test might work or not depending on JVM implementation/version (and weather...)
If the Map provided is not implementing SortedMap, the assertion should fail.

In order to not break previous behavior, maybe we can introduce a "strict" mode.

This can be applied to Set as well.

**Comment by joel-costigliola** [comment]
That's right and the [javadoc](http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractMapAssert.html#containsExactly%28org.assertj.core.data.MapEntry...%29) is clear about that  - ok I know people don't read javadoc ;-).
It actually can work with `LinkedHashMap` since it has a predictable iteration order.
