### ISSUE TITLE
Support for extracting on extracted iterables

### ISSUE THREAD

**Issue by xasx** [joel-costigliola/assertj-core#329]
Trying to reduce code with the majestic AssertJ framework :crown: , I found me recently doing something like

```java
assertThat(aList).extracting("properties").extracting("key").containsOnly("key1","key2");
```

While `aList` contained some elements with a `properties` property that was itself a list with a property called `key`, just as in

```java
List<SomeElement> aList = new ArrayList<>();

class SomeElement {
  List<WhatTheProperty> getProperties() { ... }
}

class WhatTheProperty {
  String getKey() { ... }
}
```

But my call obviously did not work, stating that
```
org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'key'.
Error when introspecting fields was :
- No getter for property 'key' in java.util.ArrayList 
Error when introspecting properties was :
  ...
```

Am I missing something here?

Is there a way to accomplish this or do we either need an `extractingIterable` or check whether an `Iterable` has been extracted when `extracting` (in other words: new feature)?

**Comment by joel-costigliola** [comment]
That's the expected behaviour, let me explain.
The result of using extracting is a new list composed of the extracted elements, if you are extracting String you will get a list of String, ex:
```java
assertThat(persons).extracting("name"); // List<String>
```

But in your case the element you extract is itself a list resulting in a list of list. Then you try to extract a property again but the object in the list is a list which obviously does not have the expected property, ex:
```java
assertThat(persons).extracting("children"); // List<List<Person>>
```

I guess what you want to do is to flatten the the list of list into a single list, if that is the case, use [`flatExtracting`](http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractIterableAssert.html#flatExtracting%28org.assertj.core.api.iterable.Extractor%29).

Let me know how it goes.

**Comment by xasx** [comment]
@joel-costigliola Thanks for pointing out `flatExtracting`.

I was indeed looking around whether there's some kind of convenience/shortcut to a util method like

```java
private static Extractor<Object, ? extends Collection<Object>> property(final String name) {

        return new Extractor<Object, Collection<Object>>() {

            @Override
            public Collection<Object> extract(Object input) {
                // not necessarily List here
                return Lists.transform((List) input, new Function() {

                    @Override
                    public Object apply(Object input) {
                        return Extractors.byName(name).extract(input);
                    }
                });
            }
        };
    }
```
Which could be used to parametrize `flatExtracting`.
