### ISSUE TITLE
Extracting multiple properties with Extractor

### ISSUE THREAD

**Issue by lpandzic** [joel-costigliola/assertj-core#331]
I'd have created a PR for this one but one question is, should the tuple be generified since the current version with single Extractor parameter keeps generic information?

**Comment by joel-costigliola** [comment]
I kind of remember having tried to use your version of generified tuple, but it conflicted with the non generic version. I gave up after a while but maybe I should give it another try.

**Comment by lpandzic** [comment]
Ok, when I get some time I'll make a PR with it, if it doesn't work I'll revert to non generified tuple version.

**Comment by PascalSchumacher** [comment]
What do you think, can this issue be closed as assertj now has `AbstractIterableAssert#extracting(Function<T, ?>... extractors)` and `AbstractObjectArrayAssert#extracting(Function<T, ?>... extractors)`?

**Comment by lpandzic** [comment]
It can if the compiler prevents you from doing something like (note that the Legolas tuple is in incorrect order):

```java
assertThat(fellowshipOfTheRing).extracting("name", "age")
                                    .contains(tuple("Boromir", 37),
                                              tuple("Sam", 38),
                                              tuple(1000, "Legolas"));
```

**Comment by scordio** [comment]
Hi @lpandzic, to resurrect this old issue:

> It can if the compiler prevents you from doing something like (note that the Legolas tuple is in incorrect order):

There is no way the compiler can infer and enforce the field types on `extracting(String...)` because only field names are available at compile time.

Currently, this is also not possible on `extracting(Function<? super ELEMENT, ?>...)` because extractors with different types can be mixed and the base element type of the resulting collection is always `Object` (see the wildcard in `Function` `R` type parameter).

Here we could have a small improvement: if all the extractors share the same result type (e.g., all strings), `contains()` and other assertions should only allow elements with the same base type. However, this would not solve your example, because a `String` and an `int` extractor are used and then `Object` would still be the base type for the tuple.

Just for completeness, `extracting(Function<? super ELEMENT, V> extractor)` is the current way to ensure full type safety when only one extractor is needed.

**Comment by lpandzic** [comment]
As far as I'm concerned, this issue can be closed.

**Comment by joel-costigliola** [comment]
Thanks for the feedback @lpandzic.
