### ISSUE TITLE
Some text mistake found in "org.assertj.core.api.SoftAssertionError" exception

### ISSUE THREAD

**Issue by superhdg** [joel-costigliola/assertj-core#346]
Hi joel-costigliola,
    I use softAssertions.assertThat and assertAll methods to determine test case result,but TestNG HTML report shows "org.assertj.core.api.SoftAssertionError: expected:<[tru]e> but was:[fals]e>",should be "org.assertj.core.api.SoftAssertionError: expected:<[true]> but was:<[false]>“.
   Please fix this issue,thanks.

**Comment by joel-costigliola** [comment]
This is the way errors are reporter when using `isEqualTo` assertion and JUnit is in the classpath.
Instead of creating a simple `AssertionError`, AssertJ creates a JUnit `ComparisonFailure` which shows the difference between actual and expected string representation.
In your case the difference between `true` and `false` (as String) are the first 3 letters.

`ComparisonFailure` are useful within IDEs because IDEs can display an highlighted difference.

In `SoftAssertionError` we might use standard `AssertionError`, I feel it's a minor issue as the error is correctly reported, it's just the format of the error that might be confusing.
