### ISSUE TITLE
Can't assert java.sql.Timestamp against a date as String

### ISSUE THREAD

**Issue by r0main** [joel-costigliola/assertj-core#351]
In previous versions (in 1.5.0 at least) this test was working fine :
```
@Test
public void testAssertJCanCompareTimestampWithString() {
	java.util.Date timestamp = new java.sql.Timestamp(1000);
	assertThat(timestamp).isEqualTo("1970-01-01T01:00:01");
}
```
In 2.0.0 this test is now failing with this message :
```
java.lang.AssertionError: 
Expecting:
 <"1970-01-01T01:00:01 (Timestamp@3e8)">
to be equal to:
 <"1970-01-01T01:00:01 (Date@3e8)">
but was not.
```

I know the method `assertThat(Date date).hasSameTimeAs(Date date)` has been added since the issue #273, it would be nice to add the same method for a String : `assertThat(Date date).hasSameTimeAs(String dateAsString)`.

**Comment by joel-costigliola** [comment]
Thanks for reporting this regression.
I have created #352  to track `assertThat(Date date).hasSameTimeAs(String dateAsString)`

**Comment by joel-costigliola** [comment]
This is not actually not a bug, the assertion fails as expected because a `Timestamp` is never equal to a `Date` according to `Timestamp` `equals` method:
```java
    public boolean equals(java.lang.Object ts) {
      if (ts instanceof Timestamp) {
        return this.equals((Timestamp)ts);
      } else {
        return false;
      }
    }
``` 
It was working in AssertJ 1.5.0 because of a bug in `isEqualTo` implementation that inverted `actual` and `expected` before comparing them, instead of comparing a `Timestamp` to a `Date` it compared a `Date` to `Timestamp` which can be equal as `Timestamp` is a `Date`.

The only thing to do in your case is to compare their time which is why `hasSameTimeAs` was added.

**Comment by snehi23** [comment]
I stumble upon the same issue and observe this interesting case. Is there any alternative for 'hasSameTimeAs' in 'hamcrest-core' libraries which I can utilize or I need to write it myself if I chose not to use 'AssertJ' ?

**Comment by joel-costigliola** [comment]
The hamcrest question should be asked to the hamcrest project but I guess it is always possible to write your own matcher.
