### ISSUE TITLE
Date in not supported pattern is parsed incorrectly without error

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#369]
Date represented as string with space instead of `T` is incorrectly parsed as date at midnight without any error. This sample illustrates problem:
```java
Date date = new Date();
Timestamp timestamp = new java.sql.Timestamp(date.getTime());
String dateAsString = timestamp.toString(); //2015-04-12 21:25:12.293
assertThat(date).isEqualTo(dateAsString);
```
Result
```
org.junit.ComparisonFailure: 
Expected :2015-04-12T00:00:00
Actual   :2015-04-12T21:25:12
```

**Comment by joel-costigliola** [comment]
Good catch, probably due to date format being lenient by default (if I'm not mistaken)

**Comment by mkordas** [comment]
That's right. Let's try to resolve it with [setLenient(false)](http://docs.oracle.com/javase/7/docs/api/java/text/DateFormat.html#setLenient(boolean)). Can I proceed with PR? Do we require additional Javadoc/release notes for such breaking-compatibility change?

**Comment by joel-costigliola** [comment]
Yes let's do that in that PR.
The commit message should say that it's a braking change so that when I do the release notes I won't forget it.

I'm thinking that we might also add a way to set the parsing leniency so that users can switch to the old behaviour. The (new) default behaviour being not to be lenient.
First though would be to add a method `setStrictDateParsing(boolean)`  in `Assertions` delegating the real work to the same method in `AbstractDateAssert`.

**Comment by mkordas** [comment]
Do we want to make it static parameter per entire ClassLoader or rather just for one assertion?

**Comment by mkordas** [comment]
One more thing - leniency mode does not solve the original problem from the issue. It solves couple more other problems with parsing, such as allowing January 32nd to be interpreted as February first or even January -1st as December 31st. More examples can be found [here](http://stackoverflow.com/questions/7606387/what-is-the-use-of-lenient). WDYT?

**Comment by joel-costigliola** [comment]
Using non lenient date parsing is a good thing, let's create an issue for that.
If leniency was the pb for this issue, we need more investigation (I haven't had the time to debug the code yet)

**Comment by mkordas** [comment]
OK, #374 created. I've got almost ready PR for that, but @joel-costigliola, can you answer my design question?

**Comment by joel-costigliola** [comment]
The problem comes from [DateFormat parse](http://docs.oracle.com/javase/7/docs/api/java/text/DateFormat.html#parse%28java.lang.String%29) that may not use the entire text of the given string. 
The default date formats supported are:

1. `yyyy-MM-dd'T'HH:mm:ss.SSS`
2. `yyyy-MM-dd'T'HH:mm:ss`
3. `yyyy-MM-dd`

The first two don't match `2015-04-12 21:25:12.293` but the third does as the start of `2015-04-12 21:25:12.293` matches `yyyy-MM-dd`.

To support `Timestamp` string representation (which unfortunately does not comply with [ISO 8601 format](http://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations), we should simply add  `yyyy-MM-dd HH:mm:ss.SSS` in default supported date formats.

**Comment by joel-costigliola** [comment]
wip ...
