### ISSUE TITLE
Iterables.toArray does not return correctly typed array

### ISSUE THREAD

**Issue by a11n** [joel-costigliola/assertj-core#398]
In order to fix #393 I wanted to use `org.assertj.core.util.Iterables#toArray` for the proposed convenience methods.

However I noticed that the aforementioned `toArray` somehow does not return a correctly typed array. It returns an array of objects instead.

Here is some test code to reproduce the issue:
```java
  @Test
  public void should_return_array_of_given_iterable_type() throws Exception {
    ArrayList<CharSequence> values = new ArrayList<>();
    values.add("one"); values.add("two");
    
    CharSequence[] result = Iterables.toArray(values);
  }
```

Fails with:
`java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.CharSequence;`

I debugged several `toArray` calls and it always returns `Object[]`.

Am I doing something wrong?

I furthermore noticed that the `Iterables` class is marked to be removed? Just curious because I am working on a contribution for #393 where this util class would be nice to have :-)

**Comment by joel-costigliola** [comment]
`Iterables` won't be removed, it's just an old comment from the fest-assert days.
More comment later on your main question.

**Comment by a11n** [comment]
Any news? :-)

**Comment by joel-costigliola** [comment]
I think this was a utility method to convert an `Iterable` to an array, it is wrong as it always returns an `Object[]` because of calling `toArray()`.

There is no way that I know of to return a generic array from an `Iterable<T>`, if you need such a method  you need to create one taking the class type as a parameter as explained here : http://stackoverflow.com/questions/6754554/reusable-method-to-transform-iterablet-to-t.

Note that assertj-core does not have dependencies by design so we can't just use guava.

**Comment by joel-costigliola** [comment]
Things are trickier than expected, your example test will never work (with or without your PR code).

It turns out that this test fails with a class cast exception in eclipse but work in maven, probably due to the eclipse compiler trying to cast `Iterables.toArray(values)` to a `String[]`
```java
@Test
public void should_return_array_of_given_iterable_elements() throws Exception {
  assertThat(Iterables.toArray(values)).containsExactly("one", "two");
}
```

however rewriting this test as always works
```java
@Test
public void should_return_array_of_given_iterable_elements() throws Exception {
  Object[] objects = Iterables.toArray(values);
  assertThat(objects).containsExactly("one", "two");
}
```

It seems that as long as you don't assign `Iterables.toArray(values)` to a "typed" array, everything runs fine ... tricky.

**Comment by a11n** [comment]
Hi Joel,

Note that I've left `Iterable.toArray` untouched (except the remark in its Javadoc). The link you posted from Stackoverflow mentioned that it's necessary to provide the type due to generic type erasure.

I've created a dedicated `toArray(Iterable<? extends T> iterable, Class<T> type)`. So the original example code from above is obsolete. Sorry if I haven't pointed out the clear enough. 

This should run `assertThat(Iterables.toArray(values, String.class)).containsExactly("one", "two");`.

Best regards,
André

**Comment by joel-costigliola** [comment]
Sorry I wasn't clear, there was nothing wrong in your PR. 
I was just saying that the existing  `Iterables.toArray(values)` only worked if you don't assign the result to a strongly typed array.
