### ISSUE TITLE
Support for Java 8 Streams

### ISSUE THREAD

**Issue by lpandzic** [joel-costigliola/assertj-core#419]
Add assertions for streams, it should contain at least the same assertions as for a List.

**Comment by joel-costigliola** [comment]
Stream assertions is indeed a nice thing to have.

**Comment by AlexBischof** [comment]
Something feels the same way wrong here as by iterator assertion. A stream is not a data structure and especially no list. Having said that i can imagine that there are usecases where you have to check the results of a stream chain (e.g. mapping, filtering...).

So basically we have to add a convenience method have we?

**Comment by lpandzic** [comment]
Ok, for start, Stream assertions should have same API methods as Iterable assertions?

**Comment by nicolaiparlog** [comment]
I guess it will become more and more common to have methods return streams so I definitely see a use case for stream assertions. :+1:

For others coming here looking for a solution: Depending on the tested method's semantics regarding order and uniqueness of stream elements, I currently usually collect them into a list or set and assert the desired properties there.

**Comment by joel-costigliola** [comment]
Implemented by converting the `Stream` to a `List` and then returning a `ListAssert`.

**Comment by dpinol** [comment]
The error report does not show the contents of the expected stream:

`assertThat(Stream.of(1)).isEqualTo(Stream.of(2));`

```
org.junit.ComparisonFailure: 
Expected :java.util.stream.ReferencePipeline$Head@14f232c4
Actual   :[1]
```

**Comment by joel-costigliola** [comment]
@dpinol it does not indeed, actual is converted to a list  that's why is is displayed "nicely".
We could display expected like a list for `isEqualTo` but it might be misleading because if will never be equal to actual because actual is a list but even if it was a Stream it would not be equal, you can verify that by executing `Stream.of(1, 2, 3).equals(Stream.of(1, 2, 3))` which returns false.

I'm not sure I want 
```java
assertThat(Stream.of(1, 2, 3)).isEqualTo(Stream.of(1, 2, 3));
``` 
to return an error like:
```
org.junit.ComparisonFailure: 
Expected :Stream(1, 2, 3)
Actual   :Stream(1, 2, 3) 
```
that would hide the fact that Stream don't override `equals`.

I think here AssertJ does not a great job at showing its limitations, Stream assertions have been implemented by converting actual to a list and then using list assertions, that works well for most of the assertions except for assertions like `isEqualTo` or `isSameAs`.

It may be time to have first class support for `Stream`, if we do so there will always be other limitations, no assertions chaining as you can only consume a stream once.

**Comment by joel-costigliola** [comment]
I don't think there is an ideal way of implementing `Stream`, converting to list assertions is nice as it supports assertions chaining. One thing we should do is to clearly inform users of the limitations/pitfalls of `Stream` assertions (the same applies for `Iterator` assertions btw)

@PascalSchumacher thoughts ?

**Comment by PascalSchumacher** [comment]
I agree.

**Comment by iheb719** [comment]
So can you please enlight us of the limitations/pitfalls of `Stream` assertions ? @joel-costigliola

**Comment by joel-costigliola** [comment]
@iheb719  will do ... in the doc. but to answer quickly the main thing is we are converting the  stream to a list under the hood so any assertions assuming it is dealing with a Stream would not work, eg: 
```
assertThat(stream).isInstanceOf(Stream.class);
```
