### ISSUE TITLE
When softly calling a custom assertion method, an assertion failure in a call to isNotNull() does not stop further execution of the method

### ISSUE THREAD

**Issue by paul-koenig** [joel-costigliola/assertj-core#447]
I have written custom assertion classes and methods following the approach described in the [official documentation](http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html).

However, when I use my custom assertion classes softly (using a custom soft assertions class that extends `SoftAssertions`), my custom assertion methods will throw `NullPointerException`s instead of failing cleanly when the object being asserted on is unexpectedly `null`.

I've documented a very simple example of what I'm doing below, as well as a couple of workarounds, neither of which I am comfortable with.

##### Example

To demonstrate this problem with familiar code, I created a project using the `TolkienCharacter` and `TolkienCharacterAssert` classes documented [here](http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html)

To make these classes operational, I added the necessary getters to the `TolkienCharacter` class and created an empty `Race` class.

Then I created a simple class to enable soft assertions on the `TolkienCharacterAssert` class.  It looks like this:

```java
import org.assertj.core.api.SoftAssertions;

public class TolkienSoftAssertions extends SoftAssertions {

        public TolkienCharacterAssert assertThat(TolkienCharacter actual) {
                return proxy(TolkienCharacterAssert.class, TolkienCharacter.class, actual);
        }
}
```
Then I created a simple class to test my `SoftAssertions`:

```java
public class Demo {
    public static void main(String[] args) {
        TolkienCharacter frodo = new TolkienCharacter();
        TolkienCharacter samnullGamgee = null;
        TolkienSoftAssertions softly = new TolkienSoftAssertions();
        softly.assertThat(frodo).hasAge(10); // Expect failure - age will be 0 due to not being initialized.
        softly.assertThat(samnullGamgee).hasAge(11); // Expect failure - argument is null.
        softly.assertAll();
    }
}
```

When I run this class, I get a `NullPointerException` when asserting on `samnullGamgee`.  It occurs in the `if`-statement in the `hasAge` method, which I've included below for convenience:

```java
public TolkienCharacterAssert hasAge(int age) {
    // check that actual TolkienCharacter we want to make assertions on is not null.
    isNotNull();

    // check condition
    if (actual.getAge() != age) {
        failWithMessage("Expected character's age to be <%s> but was <%s>", age, actual.getAge());
    }

    // return the current assertion for method chaining
    return this;
}
```
##### Workaround

I found two ways to work around this problem.

A. Update the line containing the `if`-statement to

        if (actual != null & actual.getAge() != age)

I'm not a huge fan of this approach.  It seems to defeat the purpose of the call to `isNotNull()`, and it makes the code a bit less readable.

B. Replace the line containing `isNotNull()` with

        Objects.instance().assertNotNull(info, actual)

Unfortunately, the `Objects` class is in the package `org.assertj.core.internal`, which makes me leery of using it.

**Comment by pmkpublic** [comment]
This might have the same underlying cause as the issue I described above, but I wanted to get this one documented as well.  I've noticed the same problem with assertions other ```isNotNull```.  

For example, the ```TolkienCharacterAssert.hasName``` method as written in the [documentation](http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html) will cause a ```NullPointerException``` if the ```actual != null``` and ```actual.getName() === null```.  My instinct to fix that would be add a new assertion method that validated that the name is ```null```:

```java
public TolkienCharacterAssert nameIsNotNull() {
        isNotNull();
        
        if (actual.getName() == null) {
            failWithMessage("Expected character's name to be not null but was null.");
        }
        return this;
    }
```

Then I would replace ```isNotNull()``` with ```nameIsNotNull()``` in the ```TolkienCharacterAssert.hasName``` method as below.  This would guard against ```actual``` or ```actual.getName()``` being ```null```. 

```java
public TolkienCharacterAssert hasName(String name) {
        // check that actual TolkienCharacter we want to make assertions on is not null.
        nameIsNotNull();

        // check condition
        if (!actual.getName().equals(name)) {
            failWithMessage("Expected character's name to be <%s> but was <%s>", name, actual.getName());
        }

        // return the current assertion for method chaining
        return this;
    }
```

When this version of ```hasName``` is called on a ```TolkienCharacter``` whose ```name``` is ```null```, the behavior differs depending on whether or not it is called softly.

Not softly:

```java
TolkienCharacter namelessCharacter = new TolkienCharacter(); // Name is null.
TolkienCharacterAssert.assertThat(namelessCharacter).hasName("any name");
// Result is Exception in thread "main" java.lang.AssertionError: Expected character's name to be not null but was null.
```

Softly:

```java
TolkienCharacter namelessCharacter = new TolkienCharacter(); // Name is null.
TolkienSoftAssertions softly = new TolkienSoftAssertions();
softly.assertThat(namelessCharacter).hasName("any name");
softly.assertAll();
// Result is an NPE in the call to actual.getName().equals(name) in hasName
```

**Comment by joel-costigliola** [comment]
Soft assertions internally work with proxied method, where the original method call is intercepted and any assertion error captured.

The difference between the call to `isNotNull();` and `Objects.instance().assertNotNull(info, actual)` is that the former is called is a proxied call from a proxied call, `hasName` being the outer proxied call and `isNotNull();` the inner one while the latter is normal call from a proxied call (`hasName`).

Ok, bear with me.

Like every direct call to soft assertion the error (if any) is captured and the "normal" execution flow of the program continue, this is what makes soft assertions not failing at the first assertion error.

It turns out that executing `isNotNull();` in a proxied context will make the "normal" execution flow of program continue which is executing `if (!actual.getName().equals(name))` leading to the NPE.
Note that the assertion error is correctly captured, this is why that you have it if you avoid the NPE by executing `if (actual.getName() != null && !actual.getName().equals(name))`.

On the other hand, `Objects.instance().assertNotNull(info, actual)` is not executed in an inner proxied call, it's a "normal" call, throwing an assertion error captured by the proxied `hasName`.

Now that we have the explanation, I see two solutions:
* avoid calling a proxied method in an already proxied method
* don't create a new proxy context if one already exists

The second solution is obviously the better one but I'm not sure yet it is feasible, still more investigation to do ...

**Comment by PascalSchumacher** [comment]
I guess #687 could be solved if assertj tracks the current outermost assertion method and its arguments. Once the first AssertionError occurs skip all further calls from this method.

**Comment by joel-costigliola** [comment]
fixed by rethrowing `AssertionError` from nested assertion call.
