### ISSUE TITLE
Method does not behave as expected: org.assertj.core.api.AbstractAssert.as(String, Object...)

### ISSUE THREAD

**Issue by ernesto-maserati** [joel-costigliola/assertj-core#481]
The codelines below should result in the same behavior in my opinion:

    assertThat("A").isEqualTo("B").as("Error Message");
    assertThat("A").as("Error Message").isEqualTo("B");

But the first code line does not print the error message.

Actually I prefer to write it like the first code line, but I am forced to write it like the second code line, since otherwise I won't see the error message when the assertion fails.

**Comment by joel-costigliola** [comment]
It would be nice indeed to be able to write the first line but it's not possible in the current design of AssertJ (and won't be unless a major refactoring is done). 

The reason is that AssertJ evaluates assertion in order, in your first example `isEqualTo("B")` is evaluated before `as("Error Message")` and if it fails then an assertion error is thrown which explains why `as("Error Message")` is not evaluated at all.

Should AssertJ do lazy evaluation ? That would be nice but how AssertJ would know when to evaluate the chained assertions ? that is, in your first example, how AssertJ would know that is should evaluate the assertion after `as("Error Message")` ? No easy solution to that except adding a termination method to signal AssertJ to perform the assertion but that would be verbose and not fluent (ex `assertThat("A").isEqualTo("B").as("Error Message")evaluate();`) - not a nice solution IMO.

To conclude, this is the normal behavior and it can't be improved without rewriting a major part of AssertJ.

**Comment by joel-costigliola** [comment]
closing the issue as it works as expected.

**Comment by ernesto-maserati** [comment]
Hi Joel,

the method as(...) could trigger evaluation so the method evaluate() at the
end would not be required in that case.

I don't know if it would be possible to determine by reflection
(getStacktrace()?) in the assertion methods the whole chain of assertions
in order not to raise a AssertionError before the error message is set (if
there is an as(...) method being used). But that would be costly in terms
of performance and tricky.

Maybe it is not pracicable what I suggested. But from a readers view I
still think it should not matter where i put the as(...) command, it should
be the same behavior.

**Comment by joel-costigliola** [comment]
Just to be clear, I have closed this issue not because I disagree with you but because it is a major change and I haven't found an elegant way to address it (adding `evaluate()` is not nice option IMO).
