### ISSUE TITLE
soft assertions should output line numbers or stack traces.

### ISSUE THREAD

**Issue by christophsturm** [joel-costigliola/assertj-core#492]
when soft assertions fail it's hard to see which assertion was not met. I think the best way would be to capture the linenumber or stacktrace of each soft assertion and then output them with the failure message.

**Comment by joel-costigliola** [comment]
Not sure what you mean, soft assertions shows a report of all failed assertions.
Can you give a test example ?

**Comment by joel-costigliola** [comment]
closing the issue for lack of feedback.

**Comment by fduminy** [comment]
I agree with @christophsturm since I have the same need.

Let's take the example of [SoftAssertionsTest.should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods\(\)](https://github.com/joel-costigliola/assertj-core/blob/b5e448af3b363526f25633005608a912ba51bdb2/src/test/java/org/assertj/core/api/SoftAssertionsTest.java#L109).

At [line 111](https://github.com/joel-costigliola/assertj-core/blob/b5e448af3b363526f25633005608a912ba51bdb2/src/test/java/org/assertj/core/api/SoftAssertionsTest.java#L111)
```java
softly.assertThat(BigDecimal.ZERO).isEqualTo(BigDecimal.ONE);
```
should trigger an error message containing
```java
at org.assertj.core.api.SoftAssertionsTest:111
```

So, [line 210](https://github.com/joel-costigliola/assertj-core/blob/b5e448af3b363526f25633005608a912ba51bdb2/src/test/java/org/assertj/core/api/SoftAssertionsTest.java#L210)
```java
assertThat(errors.get(0)).isEqualTo("expected:<[1]> but was:<[0]>");
```
would become
```java
assertThat(errors.get(0)).isEqualTo("expected:<[1]> but was:<[0]> (at org.assertj.core.api.SoftAssertionsTest:111)");
```

**Comment by joel-costigliola** [comment]
That would be an improvement indeed, I prefer the line number over the stack trace to keep the report readable.

**Comment by joel-costigliola** [comment]
Thanks @PascalSchumacher  and @fduminy for your work.
