### ISSUE TITLE
Assertions.assertThatThrownBy doesn't support the as/describedAs API

### ISSUE THREAD

**Issue by kristiany** [joel-costigliola/assertj-core#508]
This:
```java
    Assertions.assertThatThrownBy(something::call)
        .as("This is not OK")
        .isInstanceOf(expectedException);
``` 
yields the default message:
```
    java.lang.AssertionError: Expecting code to raise a throwable.
```

**Comment by joel-costigliola** [comment]
Indeed, thanks for reporting this.

**Comment by kristiany** [comment]
> Indeed, thanks for reporting this.

:+1:

**Comment by kristiany** [comment]
The thing is `something::call` gets evaluated in `assertThatThrownBy` (of course), so `as` never gets executed if `call` doesn't throw an exception. It's also not possible to set a description as the first call, because `as` and `describedAs` are not in the `Assertions` API, and perhaps that makes sense.

What if the Java 8 function is a regular `assertThat` construct/type, and evaluated with a `thrownBy`-method?

**Comment by joel-costigliola** [comment]
You are right, you can't pass a message to `assertThatThrownBy`, what you suggest is already possible by using `catchThrowable` inside `assertThat`:
```
assertThat(catchThrowable(() -> { throw new Exception("boom!") })).as("boom expected")
                  .isInstanceOf(Exception.class)
                  .hasMessageContaining("boom");
```
removing the `throw` will make the assertion fail:
```
java.lang.AssertionError: [boom expected] 
Expecting actual not to be null
```

**Comment by joel-costigliola** [comment]
It's worth documenting this `assertThatThrownBy`  limitation and the given alternative in the javadoc.

**Comment by kristiany** [comment]
> what you suggest is already possible by using catchThrowable inside assertThat

Nice, that works. 

> It's worth documenting this assertThatThrownBy limitation and the given alternative in the javadoc.

:+1:

**Comment by joel-costigliola** [comment]
Documented.

**Comment by mbjelac** [comment]
This results in code which begs for a comment. :(

```
assertThat(catchThrowable(() -> callSut)) // don't reduce to assertThatThrownBy because .as() won't work!
                .as("explanation")
                .isInstanceOf(ExpectedException.class);
```

Can this be fixed with `assertThatThrownBy` after all?

**Comment by joel-costigliola** [comment]
As mentioned by [kristiany](https://github.com/joel-costigliola/assertj-core/issues/508#issuecomment-152113278) there is no obvious fix for that (I'm happy to be proven wrong though).
Which clarification do you want to see in [assertThatThrownBy javadoc](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/Assertions.html#assertThatThrownBy-org.assertj.core.api.ThrowableAssert.ThrowingCallable-) ?

**Comment by mbjelac** [comment]
No chance to override `as()` in `AbstractThrowableAssert`?

**Comment by joel-costigliola** [comment]
I just recall that I believe you can use `assertThatCode` in your case:
```java
@Test
public void can_use_as_when_checking_exception() {

    final ThrowingCallable doNothing = () -> { };

     // assertion fails and "display me" appears in the assertion error
     assertThatCode(doNothing).as("display me")
          		      .isInstanceOf(Exception.class);
}
```
Would that work for you ?

**Comment by mbjelac** [comment]
It works. But I am not thrilled. :)

- confusing method name
- it works the same as asserting on a caught throwable, e.g. nothing thrown results in `Expecting actual not to be null`, which is not as helpful as `Expecting code to raise a throwable.`

**Comment by joel-costigliola** [comment]
I do agree `assertThatCode(doNothing).isInstanceOf(Exception.class);` is a bit confusing, the main usage for it was `assertThatCode(doNothing).doesNotThrowAnyExceptions()`.

I don't see any good options for this problem since `as` can not be supported in `assertThatThrownBy` but I might be missing something.

**Comment by mbjelac** [comment]
Yes, I (finally!) see the problem. `assertThatThrownBy` asserts not null on the throwable before any chained calls, `as` or otherwise. I suppose this was made so users can check whether the call through anything at all... I admit that I have indeed used this a couple of times.

The only solution I see is that we use `assertThatCode`.
However, the message in case of throwable being `null` should be fixed.

The fix: All public methods in `AbstractThrowableAssert` which check parts of the throwable (`isSameAs`, `isInstanceOf`, `hasMessage`, ...) should first call `hasBeenThrown()`.

There is no point in checking a throwable which is `null` because this is de-facto usage of a part of the `AbstractObjectAssert` API not intended for throwables. A `null` throwable is already an error, not a regular value which should be checked.

And I would prefer the method `assertThatCode` be called `assertThatCall` since that's more specific and after all, its argument is called `...Callable`.

**Comment by joel-costigliola** [comment]
I can agree with calling `hasBeenThrown()` in `AbstractThrowableAssert`.

We can't rename `assertThatCode` as it would be a breaking change, I'm a bit reluctant to  add `assertThatCall` as an alias `assertThatCode` because users might wonder what is the difference with `assertThatCode`.

**Comment by mbjelac** [comment]
Great, I am pleased. :)

I'll probably get used to the name anyway.

**Comment by joel-costigliola** [comment]
Would you be keen to contribute that ?

**Comment by mbjelac** [comment]
Riiight ... one of these days. Sorry. Got swamped with other stuff as usual.
In the meantime I stopped seeing this as important.
I'll fix it when/if I run into the issue again and it still bothers me.

**Comment by joel-costigliola** [comment]
Sure, no problem.
