### ISSUE TITLE
Path assertion for file contents is unusable if you don't use the default filesystem

### ISSUE THREAD

**Issue by fge** [joel-costigliola/assertj-core#519]
It is unusable because of this particular line:

	  File actualAsFile = actual.toFile();

This can never work for anything else than the default filesystem.

**Comment by PascalSchumacher** [comment]
Hi fge,

what version are you referring to? I can not find the `File actualAsFile = actual.toFile();` anywhere in current the codebase.

I guess this is a duplicate of https://github.com/joel-costigliola/assertj-core/issues/439 which was fixed with https://github.com/joel-costigliola/assertj-core/commit/cba1f870e41815fbf85497510d8744c1a3b6ef58 ?

**Comment by fge** [comment]
@PascalSchumacher this is mockito-core 1.10.19.

**Comment by PascalSchumacher** [comment]
>@PascalSchumacher this is mockito-core 1.10.19.

???

**Comment by fge** [comment]
Oops, sorry, brain fart...

assertj-core 3.1.0.

**Comment by PascalSchumacher** [comment]
Please give assertj-core 3.2.0 a try. The issue should be fixed in 3.2.0.

**Comment by joel-costigliola** [comment]
@fge have you checked 3.2.0 ?

**Comment by fge** [comment]
@joel-costigliola I have, and it indeed solves the problem. Thanks!

Closing issue.
