### ISSUE TITLE
hasFieldOrPropertyWithValue can't work with Atomics

### ISSUE THREAD

**Issue by alexcom** [joel-costigliola/assertj-core#707]
#### Summary
hasFieldOrPropertyWithValue when used against AtomicInteger or( I suspect) any other type from Atomic family fails to compare values and gives non-descriptive message.

#### Example

```java
public class TestAtomicInteger {

    static class TestClass{
        private AtomicInteger value = new AtomicInteger(42);
    }

    @Test
    public void testAtomicInteger() throws Exception {
        TestClass testee = new TestClass();
        Assertions.assertThat(testee).hasFieldOrPropertyWithValue("value",42);

    }
}
```
Output:
```
java.lang.AssertionError: 
Expecting
  <TestAtomicInteger$TestClass@d7b1517>
to have a property or a field named <"value"> with value
  <42>
but value was:
  <42>
	at TestAtomicInteger.testAtomicInteger(TestAtomicInteger.java:18)
...
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
The test fails because you are comparing an `AtomicInteger` with an `int`, nothing wrong here.

The error message is confusing because both value are represented the same way, for the time being only `isEqualTo` is smart enough to detect that unequals value are represented the same way and improve the representation to better differentiate them.

Example 1:
```java
@Test
public void compare_atomic_number() {
    AtomicInteger atomic = new AtomicInteger(42);
    // succeeds : we compare AtomicInteger fields, i.e. their internal values
    assertThat(atomic).isEqualToComparingFieldByField(new AtomicInteger(42));
}
```

Example 2:
```java
@Test
public void compare_atomic_number() {
    AtomicInteger atomic = new AtomicInteger(42);
    // Fail : equals is not overridden for AtomicInteger. 
    assertThat(atomic).isEqualTo(new AtomicInteger(42));
}
```
output : not that the hash and type of objects have been added, it is clear they are not the same
```
java.lang.AssertionError: 
Expecting:
 <"42 (AtomicInteger@180bc464)">
to be equal to:
 <"42 (AtomicInteger@1324409e)">
but was not.
```

Example 3:
```java
@Test
public void compare_atomic_number() {
    AtomicInteger atomic = new AtomicInteger(42);
    // Fail : AtomicInteger can't be equal to an int. 
    assertThat(atomic).isEqualTo(42);
}
```
output : not that the hash and type of objects have been added, it is clear they are not the same
```
java.lang.AssertionError: 
Expecting:
 <"42 (AtomicInteger@180bc464)">
to be equal to:
 <"42 (Integer@2a)">
but was not.
```

What we could do is improve the error message for `hasFieldOrPropertyWithValue` assertion to be behave like `isEqualTo` error message.

Since 3.5.0 it is easy to register a custom formatter for a type as shown in the (last) example below:
```java
  @Test
  public void compare_atomic_number2() {
    Assertions.registerFormatterForType(AtomicInteger.class, 
                                        value -> "AtomicInteger(" + value + ")");
    TestClass testee = new TestClass();
    // FAIL
    assertThat(testee).hasFieldOrPropertyWithValue("value", 42);
  }
```

output : note the `AtomicInteger(42)` representation for `AtomicInteger` :)
```
java.lang.AssertionError: 
Expecting
  <org.assertj.examples.NumberAssertionsExamples$TestClass@5034c75a>
to have a property or a field named <"value"> with value
  <42>
but value was:
  <AtomicInteger(42)>
```

**Comment by alexcom** [comment]
Thanks for the great explanation. All I cared about is the value. If it's
not really an issue, then OK.

Best regards,

Aleksandr Kravets

2016-07-12 12:28 GMT+03:00 Joel Costigliola <notifications@github.com>:
