### ISSUE TITLE
Add CharSequenceAssert#isNotBlank?

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#726]
e.g. check that a string is not `Null`, not empty and contains not only white-space.

My main concern is that Javas definition of white-space is broken (some characters like non-breaking space are not considered white-space characters). I would follow Guavas definition of white-space.

**Comment by joel-costigliola** [comment]
Tricky one ...
First, we also need to add `isBlank()` in order to be complete.
Second, I think we should provide java and unicode/guava version of the assertions:

- `isBlank()` : [unicode](http://unicode.org/cldr/utility/list-unicodeset.jsp?a=%5Cp%7Bwhitespace%7D) whitespace
- `isJavaBlank()` : (sad) version with Java whitespace as defined by [Character#isWhitespace](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isWhitespace(char))

**Comment by PascalSchumacher** [comment]
I'm currently working on a pull request with all four methods:
* `isBlank()`
* `isJavaBlank()` 
* `isNotBlank()`
* `isNotJavaBlank()`

**Comment by PascalSchumacher** [comment]
Since Java 5, there is also `Character#isWhitespace(int codePoint)`, 

http://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isWhitespace(int)

which includes non-breaking white-space, so maybe we should drop the (imho) ugly `isJava...` methods?

**Comment by joel-costigliola** [comment]
Does it cover guava's "definition" of blank ? I agree we should only have `isBlank`

**Comment by PascalSchumacher** [comment]
I was wrong, `Character#isWhitespace(int codePoint)` does not consider non-breaking whitespace to be whitespace:

>Determines if the specified character (Unicode code point) is white space according to Java. A character is a Java whitespace character if and only if it satisfies one of the following criteria: 
>It is a Unicode space character (SPACE_SEPARATOR, LINE_SEPARATOR, or PARAGRAPH_SEPARATOR) but is not also a non-breaking space ('\u00A0', '\u2007', '\u202F'). 

Sorry for the confusion.
