### ISSUE TITLE
Support classes of java.util.concurrent.atomic

### ISSUE THREAD

**Issue by ChristophLu** [joel-costigliola/assertj-core#746]
When using the `Atomic*` classes, we always have to write `assertThat(myAtomic.get()).isEqualTo(42)`. I think it would be better to write `assertThat(myAtomic).isEqualTo(42)` instead (without the need of calling `get()`).

**Comment by joel-costigliola** [comment]
I definitely agree to add atomic classes assertions, I'm hesitating though to use `isEqualTo` as it is meant to compare the objects with their `equals` method (whether it has overridden or not), I would prefer `hasValue` as it is clearer that you check the value inside the atomic wrapper, ex :

```java
assertThat(myAtomic).hasValue(42)
```

**Comment by ChristophLu** [comment]
Using `hasValue()` instead of `isEqualTo()` seems to better, yes.

I would do it but it may take a while since I never have done that before and do not know the AssertJ "internals". But I will try it :)
Just forking it and after completion, merge (pull request) into `master`?

**Comment by joel-costigliola** [comment]
Great ! Please create the pull request on the 2.x branch, 2.x is for Java 7 assertions, master for Java 8 (actually 2.x in regularly merged into master so that master branch = all Java 7 assertions + java 8 specific ones).

Take [`OptionalAssert`](https://github.com/joel-costigliola/assertj-core/blob/ff021db1c1cbe02b24998228d5659f5eca00d0a6/src/main/java/org/assertj/core/api/OptionalAssert.java) as an example to guide you, `OptionalAssert` provides a `hasValue` assertion.

Don't forget to write Javadoc for the assertions that show some usage examples.

The not-so-funny part is that there are many flavors of `Atomic*`, I suggest to develop one completely, let me review it and then and see if it possible to generify/commonize the code for the other atomic assertion classes.

Makes sense ?

**Comment by ChristophLu** [comment]
Makes sense! I will do it for `AtomicInteger` in the 2.x branch.

**Comment by joel-costigliola** [comment]
Note that `OptionalAssert` only exists in the master branch not 2.x since it is Java 8 (you can look at other assert classes too to guide you).

I think that designing `AtomicIntegerAssert` in a generic way (if possible) would be a great thing when we will need to implement the other atomic assert classes.

**Comment by epeee** [comment]
@joel-costigliola I did a very first implementation of this one (see the linked commit above).
I'd highly appreciate your feedback.
