### ISSUE TITLE
Allow to specify type comparator after using extracting on Object

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#752]
#### Summary

Extend `usingComparatorForElementFieldsWithType` usage to `extracting` on `Object`
#### Example

``` java
Person joe = new Person("Joe", 25);
joe.setHeight(new BigDecimal("1.80"));

assertThat(joe).extracting("name", "height")
               .usingComparatorForElementFieldsWithType(new BigDecimalComparator(), BigDecimal.class)
               .containsExactly("Joe", new BigDecimal("1.8"));
```

**Comment by joel-costigliola** [comment]
While reviewing this, I now find that `usingComparatorForElementFieldsWithType` should have been `usingComparatorForType` as I think it clear that is you register a comparator for a given type, it's gonna be used whenever an instance of this type needs to be compared.

@PascalSchumacher thoughts ?

**Comment by fiery-phoenix** [comment]
Well, `usingComparatorForElementFieldsWithType` method name does reflect current implementation behavior. Not sure if there might be cases when new behavior will not work instead of it (I mean, if there might be needed to have comparator registered for elements' fields, but not for elemetns themself). Agree that method name `usingComparatorForType` fits new behavior better.

**Comment by PascalSchumacher** [comment]
I agree that

```java
assertThat(joe).extracting("name", "height")
               .usingComparatorForType(new BigDecimalComparator(), BigDecimal.class)
               .containsExactly("Joe", new BigDecimal("1.8"));
```

reads better.

I'm not sure about deprecating `usingComparatorForElementFieldsWithType`. It think its name is well aligned with `usingComparatorForElementFieldsWithNames`. Both methods serve as a set-up for `usingFieldByFieldElementComparator`, `usingElementComparatorOnFields`, `usingElementComparatorIgnoringFields` and `usingRecursiveFieldByFieldElementComparator`. 
Furthermore the use case is different, while `usingComparatorForType` works on the elements (see above), `usingComparatorForElementFieldsWithType`  works on the fields of the elements, e.g.:

```java
public class Person {

    private final String name;

    public Person(String name) {
        this.name = name;
    }
}

@Test
public void test() {
    assertThat(new Person[] {new Person("John")})
        .usingComparatorForElementFieldsWithType(new AlwaysEqualStringComparator(), String.class)
        .usingFieldByFieldElementComparator()
        .containsExactly(new Person("Jane"));
}
```

**Comment by fiery-phoenix** [comment]
I would like to figure out what is expected from `usingComparatorForType`.

Before that I would like to mention that when `usingComparatorForElementFieldsWithType` is called, comparator for element field by type is not getting applied until `usingFieldByFieldElementComparator` (or some other setting comparator method) which uses `comparatorsForElementPropertyOrFieldTypes`  is called, as by default elements are compared by `equals.` 
For example:

This will not pass:

    Person obiwan = new Person("Obi-Wan", new BigDecimal("1.820"));
    Person obiwanClone = new Person("Obi-Wan", new BigDecimal("1.82"));`

    assertThat(asList(obiwan))
      .usingComparatorForElementFieldsWithType(new BigDecimalComparator(), BigDecimal.class)
      .containsExactly(obiwanClone);

And this will:

    assertThat(asList(obiwan))
      .usingComparatorForElementFieldsWithType(new BigDecimalComparator(), BigDecimal.class)
      .usingFieldByFieldElementComparator()
      .containsExactly(obiwanClone);

I can implement `usingComparatorForType` as:

    public <T> SELF usingComparatorForType(Comparator<T> comparator, Class<T> type) {
    if (iterables.getComparator() == null) {
      usingElementComparator(new ExtendedByTypeComparator(comparatorsForElementPropertyOrFieldTypes));
    }

    return usingComparatorForElementFieldsWithType(comparator, type);
    }

So that next will pass:

    assertThat(obiwan).extracting("name", "height")
      .usingComparatorForType(new BigDecimalComparator(), BigDecimal.class)
      .containsExactly("Obi-Wan", new BigDecimal("1.82"));

But probably there should be used different comparators map for it (not `comparatorsForElementPropertyOrFieldTypes`), lets call it `comparatorsForTypes` for now, not to affect field by field comparators. If the one to be introduced, should field by field comparators use both `comparatorsForElementPropertyOrFieldTypes` and `comparatorsForTypes`?

And should next pass:

    assertThat(obiwan).extracting("name", "height")
      .usingComparatorForType(new BigDecimalComparator(), BigDecimal.class)
      .usingFieldByFieldElementComparator()
      .containsExactly("Obi-Wan", new BigDecimal("1.82"));

when next is not passing (as of now):

    assertThat(obiwan).extracting("name", "height")
      .usingComparatorForElementFieldsWithType(new BigDecimalComparator(), BigDecimal.class)
      .usingFieldByFieldElementComparator()
      .containsExactly("Obi-Wan", new BigDecimal("1.82"));
?

**Comment by joel-costigliola** [comment]
@fiery-phoenix thanks for your comment, I agree with @PascalSchumacher to keep `usingComparatorForElementFieldsWithType` to make it clear it is only applied for element fields not elements themselves. Following that logic, I think that `usingComparatorForType` and `usingComparatorForElementFieldsWithType` should not share comparators.

Having said that, I feel adding `usingComparatorForType` is gonna confuse users, if the the difference between `usingComparatorForElementFieldsWithType` and `usingComparatorForType` might be understood, users might not get why a comparator registered with `usingComparatorForType` is not used on elements fields with the matching type, for example the following will not work:
```java
public class Person {

    private final String name;

    public Person(String name) {
        this.name = name;
    }
}

@Test
public void test() {
    assertThat(new Person[] {new Person("John")})
        .usingComparatorForType(new AlwaysEqualStringComparator(), String.class)
        .usingFieldByFieldElementComparator()
        .containsExactly(new Person("Jane"));
}
```
do you think it  is easy to understand why the test fail ?

**Comment by fiery-phoenix** [comment]
I think it will not be clear why the test you mentioned should fail. But now I have an idea what implementation could be less confusing. When have time, will update my pull request. Thank you.
