### ISSUE TITLE
Assertions.assertThat ambiguous reference error when passing a bounded generic instance

### ISSUE THREAD

**Issue by cbxp** [joel-costigliola/assertj-core#839]
#### Summary
The following code does not compile:

```java
  protected static <T extends Date> T getDate() {
    return (T) new Date();
  }
  
  @Test public void doesNotCompile()
    assertThat(getDate()).isEqualTo(getDate());
  }
```

Error:(97, 5) java: reference to assertThat is ambiguous
both method `assertThat(java.util.function.Predicate)` in org.assertj.core.api.Assertions 
and method `<T>assertThat(Object[])` in org.assertj.core.api.Assertions match

It seems that Predicate versions match because Date is Comparable?

We have this problem with many of our domain model classes...
No such problems with Junit or Hamcrest.

Anyway, it seems that adding of `assertThat(Object)` fixes the problem.

**Comment by PascalSchumacher** [comment]
With java 9.0.1 this fails with:

```
reference to assertThat is ambiguous
[ERROR] both method assertThat(java.util.function.IntPredicate) in org.assertj.core.api.Assertions
and method <T>assertThat(java.util.function.Predicate<T>) in org.assertj.core.api.Assertions match
```

**Comment by joel-costigliola** [comment]
I think that comes from the fact that the generic value could match different interfaces we have `assertThat` for, I believe it worked with java 7 as the jdk for java 7 was buggy and allowed this but java 8+ compiler don't anymore.
If I'm right, there is not much we can do except disambiguating `assertThat` methods by renaming some, for ex `assertThatComparable` but that's not something that I'm keen to do.

**Comment by joel-costigliola** [comment]
the reason why is does not compile is https://stackoverflow.com/questions/29499847/ambiguous-method-in-java-8-why

@cbxp if you are on 3.8.0 then you can use `AssertionsForClassTypes` as its `assertThat` don't take any interface types which avoids the problem completely. Unfortunately I screwed up 3.9.0 by adding  `assertThat(CompletionStage` to `AssertionsForClassTypes` :man_facepalming:.

```java
	protected static <T extends Date> T getDate() {
		return (T) new Date();
	}

	@Test
	public void doesCompile() {
		AssertionsForClassTypes.assertThat(getDate()).isEqualTo(getDate());
	}
```

**Comment by joel-costigliola** [comment]
We will add that explanation to the FAQ, you are likely not the first one to get this problem.

**Comment by joel-costigliola** [comment]
documented: http://joel-costigliola.github.io/assertj/assertj-core.html#ambiguous-compilation-error

**Comment by davidmichaelkarr** [comment]
I'm running into this issue, using version 3.21.0.  I verified that the cast fixes the problem, along with now creating a silly-looking warning in Eclipse about unnecessary casts. However, the second workaround about adding AssertionsForClassTypes seems odd.  In the comments here, you simply added that qualification, and that's what I tried.  That results in a new compilation error "Cannot infer type argument(s) for <T> extracting(Function<? super ACTUAL,T>)". However, I see that at http://joel-costigliola.github.io/assertj/assertj-core.html#ambiguous-compilation-error you say something slightly different. You ALSO added the cast to the second workaround.  That fixes the compile error on the "assertThat" call, but of course it does, because the cast itself does that.  However, adding both the "AssertionsForClassTypes ." reference AND the cast results in a different compile error, on a later predicate.

My original code line is this:
```
        assertThat(wlsCartNode.at("/losgs/losg16170729/lineItems/128579015349").withArray("payments"))
            .extracting(jn -> jn.at("/paymentTenderReference").asText())
            .doesNotContain(PaymentConstants.PAYMENT_TENDER_COF);
```
This gets the error:
```
The method assertThat(Predicate<Object>) is ambiguous for the type ...
```
If I change it to:
```
		assertThat(((JsonNode)(wlsCartNode.at("/losgs/losg16170729/lineItems/128579015349").withArray("payments"))))
				.extracting(jn -> jn.at("/paymentTenderReference").asText())
				.doesNotContain(PaymentConstants.PAYMENT_TENDER_COF);
```
It compiles without error (and works).

If I instead use the second workaround, as specified at http://joel-costigliola.github.io/assertj/assertj-core.html#ambiguous-compilation-error , not in this issue, as this:
```
        AssertionsForClassTypes.assertThat(((JsonNode)(wlsCartNode.at("/losgs/losg16170729/lineItems/128579015349").withArray("payments"))))
        .extracting(jn -> jn.at("/paymentTenderReference").asText())
        .doesNotContain(PaymentConstants.PAYMENT_TENDER_COF);
```
It gets an error on the last line, saying "The method doesNotContain(String) is undefined for the type AbstractObjectAssert<capture#75-of ?,String>".

I see that if I try to add a new predicate before that one and just enter "doesNot" and let it show me completions, it shows me "doesNotHave(Condition)" and some other related choices.

**Comment by davidmichaelkarr** [comment]
In this case (note that I didn't write this code), "doesNotContain" is not as apropos as "isNotEqualTo", which does not have this problem.

**Comment by joel-costigliola** [comment]
Hard to know if that will work without a reproducible test case but try using https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractObjectAssert.html#extracting(java.util.function.Function,org.assertj.core.api.InstanceOfAssertFactory) to narrow the extracted type to a String.

ex:
```java
// Create frodo, setting its name, age and Race
 TolkienCharacter frodo = new TolkienCharacter("Frodo", 33, HOBBIT);

 // let's extract and verify Frodo's name:
 assertThat(frodo).extracting(TolkienCharacter::getName, as(InstanceOfAssertFactories.STRING))
                  .startsWith("Fro");
```
