### ISSUE TITLE
Assert That X is Null returns void

### ISSUE THREAD

**Issue by ed0906** [joel-costigliola/assertj-core#976]
#### Summary

This may be by design but the following is not possible

`assertThat(someValue).isNull().as("Check some value is null")`

As `isNull()` returns void. All other `assertThat(someValue).someCheck(...)` return an `XXXAssert` which can be chained with an `as`.

We prefer to have the descriptions at the end for improved readability like:

```
assertThat(someValue).isNotNull()
    .as("Check some value is not null")
```

#### Example

```java
assertThat(someValue).isNull().as("Check some value is null")
```

**Comment by PascalSchumacher** [comment]
Hi Ed,

if you put the description at the end it will not be used (see: http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#describe-assertion for details).

**Comment by joel-costigliola** [comment]
It was indeed by design for `isNull` not to return anything as there is no assertions left to verify when yo know that your object is null. You will find the same behavior after `isEmpty()` iterable assertion.

@PascalSchumacher is right, an assertion description must be set **before** the assertion.

@ed0906 Can you close this issue if you feel we have answered it ? Feel free to continue the discussion otherwise.

**Comment by ed0906** [comment]
Makes sense, cheers guys!
